### ISSUE TITLE
Auto-configure path to mongo shell

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-mongodb#12]
Testing https://github.com/Microsoft/vscode/issues/25332

1) I'm connected to a local mongo db.
2) I opened the scrapbook.
3) I press <kbd>F8</kbd> on `db.getCollectionNames()`
-> I'm asked to configure mongo shell. It's on my path. It should simply be picked up from there.

<img width="1184" alt="screen shot 2017-04-27 at 8 21 24 am" src="https://cloud.githubusercontent.com/assets/4674940/25490838/eff384b6-2b22-11e7-98bf-d04a0729b2e2.png">

**Comment by StephenWeatherford** [comment]
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  

In the newest version, we will pick up mongo.exe automatically if it's in the path.

Thanks!
Stephen
