### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-mongodb#23]
I have a database in my local mongo called `admin` and it has a collection called `system.version`. I don't know where it came from unfortunately. I don't see the `system.version` collection in compass:

![image](https://cloud.githubusercontent.com/assets/1487073/26387375/eea455ec-4001-11e7-8710-fffd973362f1.png)

In VS Code, it looks like this (with errors):

![image](https://cloud.githubusercontent.com/assets/1487073/26387379/015ce9c4-4002-11e7-95e1-bbb193dd3148.png)

When I click on the `system.version` node, I get prompted to enter the path to mongo shell in the Command Palette I put in the following:

`c:\program files\mongodb\server\3.4\bin` 

which creates the following setting:

    "mongo.shell.path": "C:\\Program Files\\MongoDB\\Server\\3.4\\bin"

When I click on the `system.version` node in the explorer, I get two errors:

`Timed out executing use admin`
`Error: write EPIPE`

So there are two issues here:
- I don't know if I'm supposed to put in the folder where `mongo.exe` is, or the full path to `mongo.exe`. I did just the path and ran into problem 2
- Provide a friendly error message if the path is wrong

**Comment by DesignMitZweiS** [comment]
I'm getting this error too after setting up the path, which is:

`"mongo.shell.path": "D:\\MongoDB\\Server\\3.4\\bin"`

what to do?

**Comment by tonghuanming** [comment]
@chrisdias @DesignMitZweiS  
"mongo.shell.path": "D:\\MongoDB\\Server\\3.4\\bin\\mongo.exe"  or "D:/MongoDB/Server/3.4/bin/mongo.exe"

**Comment by StephenWeatherford** [comment]
I am closing this issue because this version of the extension is no longer supported.

If you have not already done so, please switch to using the new version of this extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb.  

Note that we've made improvements in error handling and other areas in the scrapbook, so please give it a try and let us know if there are problems.

Thanks!
Stephen
